title:  daniel's page
  # name of the site
author: Daniel Engel # name of site's author
email: daniel.j.engel@proton.me # email of site's author
url: eqdiag.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description:  <center><img src="/assets/images/jump_wiz.gif" width = 25,height = 25><h2></h2><p>Hey thanks for stopping by, I'm Daniel. </p> <p>I'm a software engineer with skills in scientific computing, computer graphics, and real-time audio. I really enjoy the low-level details common in systems programming. </p> <p>Currently, I'm working as an audio programmer at <a href="https://www.modulate.ai/">modulate</a>.</p></center>
#Personal page # description of the site (multiple lines allowed)

# Build settings
markdown: kramdown

permalink: /:slug.html
#  <img src="/assets/images/jump_wiz.gif" width = 25,height = 25>

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote-theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
